name: designimp_proj
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.1
  google_maps_flutter: ^2.5.0
  camera:
  page_transition:
  cloud_firestore:
  firebase_core: ^2.24.2

  firebase_auth:
  video_player: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true
